# ==============================================================================
# SonarCloud Configuration Properties for SecureNotes
# ==============================================================================
sonar.projectKey=Siddhantshukla1657_SecureNotes_Devops_Miniproject
sonar.organization=siddhantshukla1657

# Source and Test paths
sonar.sources=.
sonar.tests=tests

# Inclusions and Exclusions
sonar.inclusions=app.py,scripts/**
sonar.exclusions=tests/**,static/**,templates/**,demo-states/**,docs/**

# Language settings
sonar.language=py
sonar.python.version=3.12

# Encoding
sonar.sourceEncoding=UTF-8
